language: node_js
node_js:
  - lts/*
install:
  - npm ci
  - npm install -g codecov
cache:
  directories:
  - "$HOME/.npm"
script:
  # - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - npm test
  - codecov
